### PR TITLE
Build ARM targets with Bitcode enabled (-fembed-bitcode)

### PR DESCRIPTION
**Pull request by mkhon**
frameworks are suitable for projects with ENABLE_BITCODE = YES.

### CODE REVIEW

**Comment by ezathashim** [comment]
- I am having issues with Bitcode when running WatchOS and TVOS commands. Could you check to see if '-fembed-bitcode' is set for those 2 make commands? I get this sort of thing in the output:

cd build/OpenSSL/watchsimulator.i386 && CC="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator2.0.sdk -mwatchos-version-min=2.0 "

No bitcode flag

**Comment by mkhon** [comment]
My master branch has gone further to add watchOS and tvOS support. I will submit another pull request for bitcode-only stuff.

**Comment by mkhon** [comment]
ezathashim, if you need tvOS and watchOS support you can check my WIP: https://github.com/mkhon/Python-iOS-support

Only OpenSSL.framework can be built for watchOS and tvOS is done so far.

**Comment by ezathashim** [comment]
I actually found a temporary workaround by doing this:


- I modified the Makefile

TARGETS-tvOS=		appletvsimulator.x86_64 appletvos.arm64
CFLAGS-tvOS=		-mtvos-version-min=9.0
CFLAGS-appletvos.arm64=	-fembed-bitcode

TARGETS-watchOS=	watchsimulator.i386 watchos.armv7k
CFLAGS-watchOS=		-mwatchos-version-min=2.0
CFLAGS-watchos.armv7=	-fembed-bitcode

TO:

TARGETS-tvOS=		appletvsimulator.x86_64 appletvos.arm64
CFLAGS-tvOS=		-mtvos-version-min=9.0 -fembed-bitcode
CFLAGS-appletvos.arm64=	-fembed-bitcode

TARGETS-watchOS=	watchsimulator.i386 watchos.armv7k
CFLAGS-watchOS=		-mwatchos-version-min=2.0 -fembed-bitcode
CFLAGS-watchos.armv7=	-fembed-bitcode


I assumed that the CFLAGS where not being used in the watchos and tvos make code, and it worked.

**Comment by mkhon** [comment]
ezathashim,

Actually the problem was in this line:

CFLAGS-watchos.armv7=	-fembed-bitcode

Should be

CFLAGS-watchos.armv7k=	-fembed-bitcode

I pushed the fix to my master branch.

**Pull request closed without merging**
